[package]
name = "iowkit-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["iowkit.h"]

[dependencies]
libloading = "0.8"

[features]
default = []
legacy-functions = []
