[package]
name = "fastiow-rs-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastiow-rs = { path = "../fastiow-rs" }
anyhow = "1.0.81"
byteorder = "1.5.0"
embedded-hal = "1.0.0"