[package]
name = "fastiow-rs-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastiow-rs = { path = "../fastiow-rs" }
libloading = "0.8.3"
anyhow = "1.0.81"
time = "0.3.34"
byteorder = "1.5.0"